### ISSUE TITLE
Multi audio

### ISSUE THREAD

**Issue by sorrowfan** [avipatilpro/ZEE5#4]
No option to select audio language in multi audio videos. 
It always start with default audio. Hope you will find the solution

**Comment by avipatilpro** [comment]
ohk I'll Try

**Comment by avipatilpro** [comment]
give me one link of multi audio show or movie

**Comment by sorrowfan** [comment]
https://www.zee5.com/global/movies/details/run/0-0-2455

**Comment by sorrowfan** [comment]
Have you fixed, still it's default audio only?

**Comment by avipatilpro** [comment]
> Have you fixed, still it's default audio only?

contact me at telegram @AvishkarPatil
